### PR TITLE
terrad service

### PR DESCRIPTION
**Pull request by angelorc**
Terrad script for Systemd

```
curl https://raw.githubusercontent.com/terra-project/core/master/terrad.service > /etc/systemd/system/terrad.service
```

Change user and location `nano /etc/systemd/system/terrad.service`
```
ExecStart=/usr/local/bin/terrad start
User=root
```

Stream logs
```
journalctl --unit=terrad -b -f
```

### CODE REVIEW

**Comment by hanjukim** [comment]
It would nice if we have `make install_service` to register service on major linux releases.

**Comment by dokwon** [comment]
@angelorc also curious whether you think this should be a part of the core source code ... especially given the use case is likely limited to linux. @hanjukim ?

**Comment by angelorc** [comment]
@dokwon mmmm in ./etc ? or ./scripts/linux ??
Is useful for linux system

**Comment by angelorc** [comment]
> It would nice if we have `make install_service` to register service on major linux releases.

why not

**Comment by dokwon** [comment]
@angelorc right, but to justify adding this to core (because we nominally support OS X, Windows, and Linux builds), we would need to add a pipeline that supports all three major platforms. (Know most peeps that will run terrad will do it on linux) is it possible to add support for the other two?

**Comment by angelorc** [comment]
@dokwon sorry but I use only linux. But I think is possible to add a new directory like `./scripts/linux/etc/systemd/system/terrad.service` so the path suggest is for some linux distributions

**Comment by dokwon** [comment]
Not pursuing at this time. Perhaps should exist in a separate repo.

**Pull request closed without merging**
