### PR TITLE
upgrade to Cosmos SDK v0.39.2

### PR DESCRIPTION
**Pull request by alessio**
I'm preparing a new stable release update for the Cosmos SDK 0.39 Launchpad release series: cosmos/cosmos-sdk#7574

It'd be great if you could test the RC1 and give me feedback as soon as you can.

Thanks for considering.

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Comment by hanjukim** [comment]
Thanks for making this PR @alessio, we will report the result after testing it on our environments.

**Comment by hanjukim** [comment]
@alessio Except for https://github.com/cosmos/cosmos-sdk/pull/7943 the daemon had no problem with every environment.

**Comment by alessio** [comment]
Great, that will be merged ASAP

**Comment by alessio** [comment]
@hanjukim I've updated this PR. Please test again

**Comment by alessio** [comment]
@hanjukim Updated to RC3. Please note Release Candidate 3 is expected to become the v0.39.2 final release.

Testing and feedback would be greatly appreciated.

Thanks for considering.

**Comment by alessio** [comment]
Hi @hanjukim 

[Cosmos SDK v0.39.2 is out](https://blog.cosmos.network/cosmos-sdk-v0-39-2-is-out-278f35fb0240).
This updates the dependency to the final release.

Thanks for considering.

**Review by YunSuk-Yeo — APPROVED** [review]

**Pull request merged**
